functions:
- getLecTestResults:
    method: GET
    path: /lec-test-results/
    function: getLecTestResults
serverless:
  basePath: /${BRANCH}
  port: 3006
endpoints:
  local-global:
    params:
      apiVersion: '2015-03-31'
      region: eu-west-1
      endpoint: http://localhost:4000
    functions:
      getLecTestResults:
        name: cvs-svc-global-dev-getLecTestResults
  remote:
    params:
      apiVersion: '2015-03-31'
    functions:
      getLecTestResults:
        name: lec-test-results-${BRANCH}